### ISSUE TITLE
Support loading Flow from the closest node_modules/.bin directory

### ISSUE THREAD

**Issue by andreypopp** [prabirshrestha/asyncomplete-flow.vim#1]
It is useful to support flow installed in `node_modules`. For that we need to find the closest `node_modules` dir and look into its `.bin` subdirectory.

**Comment by andreypopp** [comment]
Will try to tackle that soon in a PR.

**Comment by prabirshrestha** [comment]
This was on my todo list but feel free to send a PR.

You could borrow the code from here. https://github.com/prabirshrestha/vim-lsp/blob/3d1cb74f9750af713a69e23fa915c715f46bd16c/example.vim#L40-L53 It should be easy to convert `s:find_nearest_file` to `s:find_nearest_directory`. These functions should go to asyncomplete repo as `asyncomplete#utils#find_nearest_file('.flowconfig', bufnr('%'))` and `asyncomplete#utils#find_nearest_directory('node_modules', bufnr('%'))` I would swap the params and make buffer parameter optional which would default to `bufnr('%')`. Sources should use `ctx['bufnr']` and not `bufnr('%')`.

You can then use `events` and `on_events` to cache the `flowbin_path`. This is just a pseudo code but make sure to handle cases where `config.flowbin_path` exists. You could also start the flow server when the file is loaded that way by the time you start typing the server would already have data to start sending completion results.

```vim
let s:flowbin_path = ''

function! asyncomplete#sources#flow#get_source_options(opts)
   return extend(extend({}, a:opts), {
       \ 'refresh_pattern': '\(\k\+$\|\.$\)',
       \ 'events': ['InsertEnter'],
       \ 'on_event': function('s:on_event')
       \ })
endfunction

function! s:on_event(opt, ctx, event) abort
    if a:event == 'InsertEnter'
        let s:flowbin_path = asyncomplete#utils#find_nearest_directory('node_modules', a:ctx['bufnr']) . '.bin/flow'
    endif
endfunction
```

**Comment by ahmedelgabri** [comment]
Maybe use https://github.com/jaawerth/nrun.vim?
