### ISSUE TITLE
Display Type Info

### ISSUE THREAD

**Issue by amadeus** [prabirshrestha/asyncomplete-flow.vim#6]
Ok, hopefully this is my last issue on this, but a feature request.

Currently in the popout menu you only display the source type as additional information:

![example](https://dl.dropboxusercontent.com/s/p52484e6h0yk88j/Desktopflow-plugin-testssrc_2017-07-24_01-23-20.png?dl=0)

However, Flow provides additional autocomplete data, such as the type of the object, or if it's a function, the arguments it takes, etc. It would be great to display this instead of `[Flow]` if possible.

**Comment by prabirshrestha** [comment]
This should be easy to fix. Feel free to send a PR. You need to modify `menu` here. You can use `asyncomplete#log` to see what it returns. Else I can get it in couple of days.

```
 let l:matches = map(l:res['result'], '{"word": v:val["name"], "dup": 1, "icase": 1, "menu": "[Flow]"}')
```

**Comment by prabirshrestha** [comment]
This should now be fixed by https://github.com/prabirshrestha/asyncomplete-flow.vim/pull/8 which is under a flag. Please give it a try.
